name: Java CI with Gradle

# 트리거
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행환경

    # 가상 MySQL DB 띄우기
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rungo
        ports:
          - 13306:3306
          # 상태확인
          # 체크간격
          # 응답 대기 시간
          # 재시도 횟수
        options: >- 
          --health-cmd="mysqladmin ping"  
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4 # 코드 가져오기
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # 가상서버에 Java 21(Temurin 배포판) 설치

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # 라이브러리 캐싱으로 다음 빌드 속도 효율 증가

        # JWT_SECRET 환경변수 주입 후 테스트 실행
      - name: Build with Gradle
        env:
          JWT_SECRET: test-secret-key-at-least-32-bytes-long
        run: ./gradlew build # 테스트 코드 전체 실행. 하나라도 실패하면 빌드 중단